name: "❌ 콘텐츠를 삭제하고 싶어요!"
description: "내용이 이상하거나, 접속되지 않을때."
labels:
  - ":page_with_curl:내용삭제"

body:
  - id: link
    type: input
    validations:
      required: true
    attributes:
      label: 🔗 링크
      description: 삭제하고 싶은 링크를 이곳에 입력해주세요.
      placeholder: "https://example.com"
  - id: about
    type: textarea
    attributes:
      label: 🧤 설명
      description: 설명을 간단하게 적어주세요.
  - type: markdown
    attributes:
      value: 공유해주셔서 감사합니다! 🙇 🙇‍